name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build React project
      - name: Build
        run: yarn build --mode production
        env:
          VITE_PRODUCTION_ENDPOINT: ${{ secrets.VITE_PRODUCTION_ENDPOINT }}
          VITE_DEVELOP_ENDPOINT: ${{ secrets.VITE_DEVELOP_ENDPOINT }}

      # Upload dist folder to server
      - name: Deploy to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "dist/"
          target: "httpdocs/"
          strip_components: 1

